name: Publish
on:
    push:
        branches:
            - develop
            - main
            - working/*

jobs:
    build-develop:
        runs-on: ubuntu-latest
        environment: test
        if: github.ref != 'refs/heads/main'
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.8
              uses: actions/setup-python@v3
              with:
                  python-version: 3.8
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: Build and publish
              run: |
                  python -m build .
            - name: Publish to PyPI Test
              if: github.ref != 'refs/heads/main'
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                skip_existing: true
                repository_url: https://test.pypi.org/legacy/
                password: ${{ secrets.PYPI_TEST_TOKEN }}
    
    build-main:
        runs-on: ubuntu-latest
        environment: production
        if: github.ref == 'refs/heads/main'
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.8
              uses: actions/setup-python@v3
              with:
                  python-version: 3.8
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: Build and publish
              run: |
                  python -m build .
            - name: Publish to PyPI Test
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                password: ${{ secrets.PYPI_TOKEN }}
            
