name: Publish
on:
  push:
    branches:
      - develop
      - main
      - working/*
permissions:
  contents: write

jobs:
  build-develop:
    runs-on: ubuntu-latest
    environment: test
    if: github.ref != 'refs/heads/main'
    outputs:
      version: ${{ steps.get_release_name.outputs.version }}
      tag_exists: ${{ steps.get_release_name.outputs.tag_exists }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
            python-version: 3.8

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - name: Build and publish
        run: |
            python -m build .

      - name: Publish to PyPI Test
        if: github.ref != 'refs/heads/main'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.PYPI_TEST_TOKEN }}

      - name: Get release Name
        id: get_release_name
        run: |
          echo "version=$(python setup.py --version)-test" >> $GITHUB_OUTPUT
          if git rev-parse "${{ steps.get_release_name.outputs.version }}" >/dev/null 2>&1; then
            echo "tag_exists=true" >> $GITHUB_OUTPUT
          else
            echo "tag_exists=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Tag commit
        if: ${{ steps.get_release_name.outputs.tag_exists }} == 'false'
        run: |
          git tag ${{ steps.get_release_name.outputs.version }}
          git push origin ${{ steps.get_release_name.outputs.version }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: ${{ steps.get_release_name.outputs.tag_exists }} == 'false'
        with:
          files: ./dist/*.whl
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
          prerelease: true
          tag_name: ${{ steps.get_release_name.outputs.version }}
          name: ${{ steps.get_release_name.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  build-main:
    runs-on: ubuntu-latest
    environment: production
    if: github.ref == 'refs/heads/main'
    outputs:
      version: ${{ steps.get_release_name.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
            python-version: 3.8

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - name: Build and publish
        run: |
            python -m build .

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}

      - name: Get release Name
        id: get_release_name
        run: |
          echo "version=$(python setup.py --version)" >> $GITHUB_OUTPUT
          if git rev-parse "${{ steps.get_release_name.outputs.version }}" >/dev/null 2>&1; then
            echo "tag_exists=true" >> $GITHUB_OUTPUT
          else
            echo "tag_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Tag commit
        if: ${{ steps.get_release_name.outputs.tag_exists }} == 'false'
        run: |
          git tag ${{ steps.get_release_name.outputs.version }}
          git push origin ${{ steps.get_release_name.outputs.version }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: ${{ steps.get_release_name.outputs.tag_exists }} == 'false'
        with:
          files: ./dist/*.whl
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
          tag_name: ${{ steps.get_release_name.outputs.version }}
          name: ${{ steps.get_release_name.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
